INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAF-001","SV04.5","Pineco","1","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAF-002","SV04.5","ForretressEX","2","1","4");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAF-003","SV04.5","Maractus","3","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAF-004","SV04.5","Toedscool","4","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAF-005","SV04.5","ToedscruelEX","5","1","4");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAF-006","SV04.5","EspathraEX","6","1","4");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAF-007","SV04.5","Charmander","7","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAF-008","SV04.5","Charmeleon","8","1","2");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAF-009","SV04.5","Magmar","9","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAF-010","SV04.5","Magmortar","10","1","3");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAF-011","SV04.5","Numel","11","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAF-012","SV04.5","Camerupt","12","1","2");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAF-013","SV04.5","Heat Rotom","13","1","3");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAF-014","SV04.5","Charcadet","14","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAF-015","SV04.5","Armarouge","15","1","3");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAF-016","SV04.5","Lapras","16","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAF-017","SV04.5","Frigibax","17","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAF-018","SV04.5","Pikachu","18","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAF-019","SV04.5","Raichu","19","1","3");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAF-020","SV04.5","Chinchou","20","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAF-021","SV04.5","Lanturn","21","1","2");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAF-022","SV04.5","Kilowattrel","22","1","2");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAF-023","SV04.5","Exeggcute","23","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAF-024","SV04.5","Exeggutor","24","1","3");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAF-025","SV04.5","Natu","25","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAF-026","SV04.5","Xatu","26","1","3");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAF-027","SV04.5","Ralts","27","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAF-028","SV04.5","Kirlia","28","1","2");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAF-029","SV04.5","GardevoirEX","29","1","4");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAF-030","SV04.5","Chimecho","30","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAF-031","SV04.5","Mime Jr.","31","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAF-032","SV04.5","Woobat","32","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAF-033","SV04.5","Swoobat","33","1","2");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAF-034","SV04.5","Cottonee","34","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAF-035","SV04.5","Whimsicott","35","1","2");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAF-036","SV04.5","Dedenne","36","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAF-037","SV04.5","Mimikyu","37","1","3");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAF-038","SV04.5","Fidough","38","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAF-039","SV04.5","Dachsbun","39","1","2");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAF-040","SV04.5","Ceruledge","40","1","3");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAF-041","SV04.5","Flittle","41","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAF-042","SV04.5","Greavard","42","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAF-043","SV04.5","Houndstone","43","1","3");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAF-044","SV04.5","Gimmighoul","44","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAF-045","SV04.5","Mankey","45","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAF-046","SV04.5","Primeape","46","1","2");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAF-047","SV04.5","Annihilape","47","1","3");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAF-048","SV04.5","Phanpy","48","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAF-049","SV04.5","Donphan","49","1","2");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAF-050","SV04.5","Barboach","50","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAF-051","SV04.5","Clobbopus","51","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAF-052","SV04.5","Grapploct","52","1","2");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAF-053","SV04.5","Great TuskEX","53","1","4");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAF-054","SV04.5","CharizardEX","54","1","4");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAF-055","SV04.5","Gastly","55","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAF-056","SV04.5","Haunter","56","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAF-057","SV04.5","Gengar","57","1","2");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAF-058","SV04.5","Paldean Wooper","58","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAF-059","SV04.5","Paldean ClodsireEX","59","1","4");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAF-060","SV04.5","Scraggy","60","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAF-061","SV04.5","Scrafty","61","1","2");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAF-062","SV04.5","Maschiff","62","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAF-063","SV04.5","Mabosstiff","63","1","3");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAF-064","SV04.5","Varoom","64","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAF-065","SV04.5","Revavroom","65","1","3");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAF-066","SV04.5","Iron TreadsEX","66","1","4");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAF-067","SV04.5","Gholdengo","67","1","3");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAF-068","SV04.5","Noibat","68","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAF-069","SV04.5","NoivernEX","69","1","4");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAF-070","SV04.5","Cyclizar","70","1","3");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAF-071","SV04.5","Lechonk","71","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAF-072","SV04.5","Oinkologne","72","1","2");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAF-073","SV04.5","Tandemaus","73","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAF-074","SV04.5","Maushold","74","1","2");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAF-075","SV04.5","SquawkabillyEX","75","1","4");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAF-076","SV04.5","Artazon","76","2","2");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAF-077","SV04.5","Atticus","77","2","2");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAF-078","SV04.5","Clive","78","2","2");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAF-079","SV04.5","Electric Generator","79","2","2");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAF-080","SV04.5","Iono","80","2","2");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAF-081","SV04.5","Moonlit Hill","81","2","2");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAF-082","SV04.5","Nemona","82","2","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAF-083","SV04.5","Nemona's Backpack","83","2","2");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAF-084","SV04.5","Nest Ball","84","2","2");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAF-085","SV04.5","Paldean Student","85","2","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAF-086","SV04.5","Paldean Student","86","2","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAF-087","SV04.5","Professor's Research [Professor Sada]","87","2","3");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAF-088","SV04.5","Professor's Research [Professor Turo]","88","2","3");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAF-089","SV04.5","Rare Candy","89","2","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAF-090","SV04.5","Technical Machine: Crisis Punch","90","2","2");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAF-091","SV04.5","Ultra Ball","91","2","2");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAF-092","SV04.5","Oddish","92","1","9");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAF-093","SV04.5","Gloom","93","1","9");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAF-094","SV04.5","Vileplume","94","1","9");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAF-095","SV04.5","Scyther","95","1","9");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAF-096","SV04.5","Hoppip","96","1","9");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAF-097","SV04.5","Skiploom","97","1","9");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAF-098","SV04.5","Jumpluff","98","1","9");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAF-099","SV04.5","Pineco","99","1","9");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAF-100","SV04.5","Snover","100","1","9");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAF-101","SV04.5","Abomasnow","101","1","9");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAF-102","SV04.5","Smoliv","102","1","9");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAF-103","SV04.5","Dolliv","103","1","9");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAF-104","SV04.5","Arboliva","104","1","9");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAF-105","SV04.5","Toedscool","105","1","9");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAF-106","SV04.5","Capsakid","106","1","9");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAF-107","SV04.5","Scovillain","107","1","9");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAF-108","SV04.5","Rellor","108","1","9");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAF-109","SV04.5","Charmander","109","1","9");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAF-110","SV04.5","Charmeleon","110","1","9");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAF-111","SV04.5","Paldean Tauros","111","1","9");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAF-112","SV04.5","Entei","112","1","9");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAF-113","SV04.5","Oricorio","113","1","9");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAF-114","SV04.5","Charcadet","114","1","9");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAF-115","SV04.5","Armarouge","115","1","9");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAF-116","SV04.5","Slowpoke","116","1","9");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAF-117","SV04.5","Slowbro","117","1","9");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAF-118","SV04.5","Staryu","118","1","9");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAF-119","SV04.5","Starmie","119","1","9");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAF-120","SV04.5","Paldean Tauros","120","1","9");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAF-121","SV04.5","Wiglett","121","1","9");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAF-122","SV04.5","Wugtrio","122","1","9");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAF-123","SV04.5","Finizen","123","1","9");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAF-124","SV04.5","Palafin","124","1","9");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAF-125","SV04.5","Veluza","125","1","9");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAF-126","SV04.5","Dondozo","126","1","9");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAF-127","SV04.5","Tatsugiri","127","1","9");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAF-128","SV04.5","Frigibax","128","1","9");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAF-129","SV04.5","Arctibax","129","1","9");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAF-130","SV04.5","Baxcalibur","130","1","9");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAF-131","SV04.5","Pikachu","131","1","9");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAF-132","SV04.5","Raichu","132","1","9");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAF-133","SV04.5","Voltorb","133","1","9");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAF-134","SV04.5","Electrode","134","1","9");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAF-135","SV04.5","Shinx","135","1","9");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAF-136","SV04.5","Luxio","136","1","9");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAF-137","SV04.5","Luxray","137","1","9");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAF-138","SV04.5","Pachirisu","138","1","9");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAF-139","SV04.5","Thundurus","139","1","9");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAF-140","SV04.5","Toxel","140","1","9");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAF-141","SV04.5","Toxtricity","141","1","9");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAF-142","SV04.5","Pawmi","142","1","9");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAF-143","SV04.5","Pawmo","143","1","9");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAF-144","SV04.5","Pawmot","144","1","9");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAF-145","SV04.5","Wattrel","145","1","9");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAF-146","SV04.5","Kilowattrel","146","1","9");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAF-147","SV04.5","Wigglytuff","147","1","9");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAF-148","SV04.5","Abra","148","1","9");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAF-149","SV04.5","Kadabra","149","1","9");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAF-150","SV04.5","Cleffa","150","1","9");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAF-151","SV04.5","Natu","151","1","9");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAF-152","SV04.5","Xatu","152","1","9");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAF-153","SV04.5","Ralts","153","1","9");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAF-154","SV04.5","Kirlia","154","1","9");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAF-155","SV04.5","Drifloon","155","1","9");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAF-156","SV04.5","Drifblim","156","1","9");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAF-157","SV04.5","Mime Jr.","157","1","9");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAF-158","SV04.5","Spiritomb","158","1","9");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAF-159","SV04.5","Klefki","159","1","9");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAF-160","SV04.5","Mimikyu","160","1","9");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAF-161","SV04.5","Dachsbun","161","1","9");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAF-162","SV04.5","Ceruledge","162","1","9");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAF-163","SV04.5","Rabsca","163","1","9");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAF-164","SV04.5","Flittle","164","1","9");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAF-165","SV04.5","Tinkatink","165","1","9");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAF-166","SV04.5","Tinkatuff","166","1","9");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAF-167","SV04.5","Tinkaton","167","1","9");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAF-168","SV04.5","Houndstone","168","1","9");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAF-169","SV04.5","Mankey","169","1","9");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAF-170","SV04.5","Primeape","170","1","9");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAF-171","SV04.5","Annihilape","171","1","9");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAF-172","SV04.5","Paldean Tauros","172","1","9");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAF-173","SV04.5","Riolu","173","1","9");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAF-174","SV04.5","Lucario","174","1","9");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAF-175","SV04.5","Hawlucha","175","1","9");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAF-176","SV04.5","Nacli","176","1","9");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAF-177","SV04.5","Naclstack","177","1","9");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAF-178","SV04.5","Garganacl","178","1","9");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAF-179","SV04.5","Glimmet","179","1","9");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAF-180","SV04.5","Paldean Wooper","180","1","9");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAF-181","SV04.5","Murkrow","181","1","9");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAF-182","SV04.5","Sneasel","182","1","9");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAF-183","SV04.5","Weavile","183","1","9");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAF-184","SV04.5","Sableye","184","1","9");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAF-185","SV04.5","Pawniard","185","1","9");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAF-186","SV04.5","Bisharp","186","1","9");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAF-187","SV04.5","Kingambit","187","1","9");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAF-188","SV04.5","Mabosstiff","188","1","9");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAF-189","SV04.5","Shroodle","189","1","9");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAF-190","SV04.5","Grafaiai","190","1","9");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAF-191","SV04.5","Scizor","191","1","9");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAF-192","SV04.5","Varoom","192","1","9");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAF-193","SV04.5","Revavroom","193","1","9");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAF-194","SV04.5","Noibat","194","1","9");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAF-195","SV04.5","Cyclizar","195","1","9");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAF-196","SV04.5","Pidgey","196","1","9");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAF-197","SV04.5","Pidgeotto","197","1","9");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAF-198","SV04.5","Jigglypuff","198","1","9");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAF-199","SV04.5","Doduo","199","1","9");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAF-200","SV04.5","Dodrio","200","1","9");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAF-201","SV04.5","Ditto","201","1","9");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAF-202","SV04.5","Snorlax","202","1","9");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAF-203","SV04.5","Wingull","203","1","9");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAF-204","SV04.5","Pelipper","204","1","9");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAF-205","SV04.5","Skwovet","205","1","9");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAF-206","SV04.5","Greedent","206","1","9");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAF-207","SV04.5","Lechonk","207","1","9");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAF-208","SV04.5","Oinkologne","208","1","9");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAF-209","SV04.5","Tandemaus","209","1","9");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAF-210","SV04.5","Maushold","210","1","9");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAF-211","SV04.5","Flamigo","211","1","9");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAF-212","SV04.5","ForretressEX","212","1","10");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAF-213","SV04.5","ToedscruelEX","213","1","10");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAF-214","SV04.5","EspathraEX","214","1","10");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAF-215","SV04.5","AlakazamEX","215","1","10");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAF-216","SV04.5","MewEX","216","1","10");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAF-217","SV04.5","GardevoirEX","217","1","10");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAF-218","SV04.5","GlimmoraEX","218","1","10");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAF-219","SV04.5","Paldean ClodsireEX","219","1","10");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAF-220","SV04.5","NoivernEX","220","1","10");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAF-221","SV04.5","PidgeotEX","221","1","10");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAF-222","SV04.5","WigglytuffEX","222","1","10");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAF-223","SV04.5","SquawkabillyEX","223","1","10");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAF-224","SV04.5","Wugtrio","224","1","5");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAF-225","SV04.5","Palafin","225","1","5");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAF-226","SV04.5","Pawmi","226","1","5");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAF-227","SV04.5","Clive","227","2","6");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAF-228","SV04.5","Judge","228","2","6");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAF-229","SV04.5","Nemona","229","2","6");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAF-230","SV04.5","Paldean Student","230","2","6");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAF-231","SV04.5","Paldean Student","231","2","6");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAF-232","SV04.5","MewEX","232","1","7");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAF-233","SV04.5","GardevoirEX","233","1","7");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAF-234","SV04.5","CharizardEX","234","1","7");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAF-235","SV04.5","Arven","235","2","7");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAF-236","SV04.5","Clive","236","2","7");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAF-237","SV04.5","Iono","237","2","7");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAF-238","SV04.5","Nemona","238","2","7");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAF-239","SV04.5","Penny","239","2","7");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAF-240","SV04.5","Wo-ChienEX","240","1","8");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAF-241","SV04.5","Chi-YuEX","241","1","8");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAF-242","SV04.5","Chien-PaoEX","242","1","8");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAF-243","SV04.5","MiraidonEX","243","1","8");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAF-244","SV04.5","Ting-LuEX","244","1","8");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAF-245","SV04.5","KoraidonEX","245","1","8");