INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("SFA-001","SV06.5","Joltik","1","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("SFA-002","SV06.5","Galvantula","2","1","2");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("SFA-003","SV06.5","Rowlet","3","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("SFA-004","SV06.5","Dartrix","4","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("SFA-005","SV06.5","Decidueye","5","1","2");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("SFA-006","SV06.5","Tapu Bulu","6","1","3");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("SFA-007","SV06.5","Houndour","7","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("SFA-008","SV06.5","Houndoom","8","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("SFA-009","SV06.5","Iron Moth","9","1","2");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("SFA-010","SV06.5","Horsea","10","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("SFA-011","SV06.5","Seadra","11","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("SFA-012","SV06.5","Kingdra","12","1","4");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("SFA-013","SV06.5","Sneasel","13","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("SFA-014","SV06.5","Weavile","14","1","2");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("SFA-015","SV06.5","Revavroom","15","1","4");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("SFA-016","SV06.5","Drowzee","16","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("SFA-017","SV06.5","Hypno","17","1","2");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("SFA-018","SV06.5","Duskull","18","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("SFA-019","SV06.5","Dusclops","19","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("SFA-020","SV06.5","Dusknoir","20","1","3");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("SFA-021","SV06.5","Cresselia","21","1","3");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("SFA-022","SV06.5","Sylveon","22","1","2");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("SFA-023","SV06.5","Croagunk","23","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("SFA-024","SV06.5","Toxicroak","24","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("SFA-025","SV06.5","Bloodmoon Ursaluna","25","1","3");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("SFA-026","SV06.5","Slither Wing","26","1","2");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("SFA-027","SV06.5","Zubat","27","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("SFA-028","SV06.5","Golbat","28","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("SFA-029","SV06.5","Crobat","29","1","2");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("SFA-030","SV06.5","Absol","30","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("SFA-031","SV06.5","Zorua","31","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("SFA-032","SV06.5","Zoroark","32","1","3");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("SFA-033","SV06.5","Inkay","33","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("SFA-034","SV06.5","Malamar","34","1","2");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("SFA-035","SV06.5","Yveltal","35","1","2");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("SFA-036","SV06.5","Okidogi","36","1","4");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("SFA-037","SV06.5","Munkidori","37","1","4");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("SFA-038","SV06.5","Fezandipiti","38","1","4");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("SFA-039","SV06.5","Pecharunt","39","1","4");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("SFA-040","SV06.5","Genesect","40","1","2");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("SFA-041","SV06.5","Cufant","41","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("SFA-042","SV06.5","Copperajah","42","1","3");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("SFA-043","SV06.5","Varoom","43","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("SFA-044","SV06.5","Axew","44","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("SFA-045","SV06.5","Fraxure","45","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("SFA-046","SV06.5","Haxorus","46","1","3");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("SFA-047","SV06.5","Kyurem","47","1","2");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("SFA-048","SV06.5","Meowth","48","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("SFA-049","SV06.5","Persian","49","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("SFA-050","SV06.5","Eevee","50","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("SFA-051","SV06.5","Furfrou","51","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("SFA-052","SV06.5","Stufful","52","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("SFA-053","SV06.5","Bewear","53","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("SFA-054","SV06.5","Academy at Night","54","2","2");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("SFA-055","SV06.5","Binding Mochi","55","2","2");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("SFA-056","SV06.5","Cassiopeia","56","2","2");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("SFA-057","SV06.5","Colress's Tenacity","57","2","2");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("SFA-058","SV06.5","Dangerous Laser","58","2","11");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("SFA-059","SV06.5","Janine's Secret Art","59","2","2");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("SFA-060","SV06.5","Neutralization Zone","60","2","11");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("SFA-061","SV06.5","Night Stretcher","61","2","2");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("SFA-062","SV06.5","Poké Vital A","62","2","11");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("SFA-063","SV06.5","Powerglass","63","2","2");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("SFA-064","SV06.5","Xerosic's Machinations","64","2","2");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("SFA-065","SV06.5","Tapu Bulu","65","1","5");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("SFA-066","SV06.5","Houndoom","66","1","5");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("SFA-067","SV06.5","Horsea","67","1","5");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("SFA-068","SV06.5","Duskull","68","1","5");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("SFA-069","SV06.5","Dusclops","69","1","5");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("SFA-070","SV06.5","Dusknoir","70","1","5");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("SFA-071","SV06.5","Cresselia","71","1","5");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("SFA-072","SV06.5","Munkidori","72","1","5");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("SFA-073","SV06.5","Fezandipiti","73","1","5");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("SFA-074","SV06.5","Okidogi","74","1","5");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("SFA-075","SV06.5","Zorua","75","1","5");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("SFA-076","SV06.5","Cufant","76","1","5");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("SFA-077","SV06.5","Fraxure","77","1","5");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("SFA-078","SV06.5","Persian","78","1","5");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("SFA-079","SV06.5","Bewear","79","1","5");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("SFA-080","SV06.5","Kingdra","80","1","6");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("SFA-081","SV06.5","Revavroom","81","1","6");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("SFA-082","SV06.5","Okidogi","82","1","6");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("SFA-083","SV06.5","Munkidori","83","1","6");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("SFA-084","SV06.5","Fezandipiti","84","1","6");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("SFA-085","SV06.5","Pecharunt","85","1","6");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("SFA-086","SV06.5","Cassiopeia","86","2","6");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("SFA-087","SV06.5","Colress's Tenacity","87","2","6");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("SFA-088","SV06.5","Janine's Secret Art","88","2","6");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("SFA-089","SV06.5","Xerosic's Machinations","89","2","6");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("SFA-090","SV06.5","Okidogi","90","1","7");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("SFA-091","SV06.5","Munkidori","91","1","7");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("SFA-092","SV06.5","Fezandipiti","92","1","7");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("SFA-093","SV06.5","Pecharunt","93","1","7");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("SFA-094","SV06.5","Cassiopeia","94","2","7");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("SFA-095","SV06.5","Pecharunt","95","1","8");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("SFA-096","SV06.5","Earthen Vessel","96","2","8");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("SFA-097","SV06.5","Powerglass","97","2","8");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("SFA-098","SV06.5","Basic Darkness Energy","98","3","8");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("SFA-099","SV06.5","Basic Metal Energy","99","3","8");