INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-001","SV04","Surskit","1","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-002","SV04","Masquerain","2","1","2");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-003","SV04","FroslassEX","3","1","4");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-004","SV04","Pansage","4","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-005","SV04","Simisage","5","1","2");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-006","SV04","Dwebble","6","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-007","SV04","Crustle","7","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-008","SV04","Bounsweet","8","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-009","SV04","Steenee","9","1","2");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-010","SV04","Blipbug","10","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-011","SV04","Dottler","11","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-012","SV04","Orbeetle","12","1","2");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-013","SV04","Nymble","13","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-014","SV04","Nymble","14","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-015","SV04","Toedscool","15","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-016","SV04","Toedscool","16","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-017","SV04","Toedscruel","17","1","2");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-018","SV04","Wo-Chien","18","1","3");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-019","SV04","Magby","19","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-020","SV04","Pansear","20","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-021","SV04","Simisear","21","1","2");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-022","SV04","Volcanion","22","1","3");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-023","SV04","Fuecoco","23","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-024","SV04","Crocalor","24","1","2");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-025","SV04","Charcadet","25","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-026","SV04","Charcadet","26","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-027","SV04","ArmarougeEX","27","1","4");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-028","SV04","Iron Moth","28","1","3");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-029","SV04","Chi-Yu","29","1","3");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-030","SV04","Horsea","30","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-031","SV04","Seadra","31","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-032","SV04","Kingdra","32","1","3");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-033","SV04","Remoraid","33","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-034","SV04","Octillery","34","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-035","SV04","Feebas","35","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-036","SV04","Milotic","36","1","3");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-037","SV04","Snorunt","37","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-038","SV04","GarchompEX","38","1","4");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-039","SV04","Mantyke","39","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-040","SV04","Palkia","40","1","3");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-041","SV04","Panpour","41","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-042","SV04","Simipour","42","1","2");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-043","SV04","Vanillite","43","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-044","SV04","Vanillish","44","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-045","SV04","Vanilluxe","45","1","2");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-046","SV04","TsareenaEX","46","1","4");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-047","SV04","Wimpod","47","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-048","SV04","Wimpod","48","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-049","SV04","Golisopod","49","1","3");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-050","SV04","GolisopodEX","50","1","4");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-051","SV04","Wiglett","51","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-052","SV04","Wiglett","52","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-053","SV04","Wugtrio","53","1","2");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-054","SV04","Veluza","54","1","2");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-055","SV04","Dondozo","55","1","2");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-056","SV04","Iron Bundle","56","1","2");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-057","SV04","Chien-Pao","57","1","3");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-058","SV04","MewtwoEX","58","1","4");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-059","SV04","Elekid","59","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-060","SV04","Plusle","60","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-061","SV04","Minun","61","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-062","SV04","Blitzle","62","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-063","SV04","Zebstrika","63","1","2");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-064","SV04","Joltik","64","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-065","SV04","Galvantula","65","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-066","SV04","Zekrom","66","1","3");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-067","SV04","Oricorio","67","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-068","SV04","Tapu KokoEX","68","1","4");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-069","SV04","Toxel","69","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-070","SV04","Iron HandsEX","70","1","4");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-071","SV04","Natu","71","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-072","SV04","Xatu","72","1","3");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-073","SV04","Latios","73","1","3");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-074","SV04","Deoxys","74","1","3");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-075","SV04","Yamask","75","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-076","SV04","CofagrigusEX","76","1","4");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-077","SV04","Pumpkaboo","77","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-078","SV04","Gourgeist","78","1","2");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-079","SV04","Flittle","79","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-080","SV04","Flittle","80","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-081","SV04","Espathra","81","1","3");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-082","SV04","Tinkatink","82","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-083","SV04","Tinkatink","83","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-084","SV04","Tinkatuff","84","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-085","SV04","Tinkaton","85","1","2");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-086","SV04","Scream Tail","86","1","2");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-087","SV04","Gimmighoul","87","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-088","SV04","Gimmighoul","88","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-089","SV04","Iron ValiantEX","89","1","4");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-090","SV04","Onix","90","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-091","SV04","Gligar","91","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-092","SV04","Gliscor","92","1","2");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-093","SV04","Groudon","93","1","3");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-094","SV04","Gible","94","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-095","SV04","Gabite","95","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-096","SV04","Mienfoo","96","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-097","SV04","Mienshao","97","1","2");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-098","SV04","HoopaEX","98","1","4");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-099","SV04","Minior","99","1","2");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-100","SV04","ToxtricityEX","100","1","4");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-101","SV04","Nacli","101","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-102","SV04","Nacli","102","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-103","SV04","Naclstack","103","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-104","SV04","Garganacl","104","1","3");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-105","SV04","Klawf","105","1","2");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-106","SV04","Flamigo","106","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-107","SV04","Slither Wing","107","1","2");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-108","SV04","Sandy ShocksEX","108","1","4");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-109","SV04","Ting-Lu","109","1","3");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-110","SV04","Zubat","110","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-111","SV04","Golbat","111","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-112","SV04","Crobat","112","1","2");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-113","SV04","Absol","113","1","2");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-114","SV04","Purrloin","114","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-115","SV04","Liepard","115","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-116","SV04","Trubbish","116","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-117","SV04","Garbodor","117","1","2");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-118","SV04","Yveltal","118","1","3");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-119","SV04","Nickit","119","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-120","SV04","Thievul","120","1","3");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-121","SV04","Morpeko","121","1","3");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-122","SV04","Lokix","122","1","3");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-123","SV04","Brute Bonnet","123","1","3");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-124","SV04","Roaring MoonEX","124","1","4");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-125","SV04","Steelix","125","1","3");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-126","SV04","Jirachi","126","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-127","SV04","Ferroseed","127","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-128","SV04","Ferrothorn","128","1","2");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-129","SV04","Durant","129","1","2");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-130","SV04","Honedge","130","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-131","SV04","Honedge","131","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-132","SV04","Doublade","132","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-133","SV04","Doublade","133","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-134","SV04","Aegislash","134","1","3");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-135","SV04","AegislashEX","135","1","4");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-136","SV04","Zacian","136","1","3");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-137","SV04","SkeledirgeEX","137","1","4");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-138","SV04","Orthworm","138","1","2");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-139","SV04","GholdengoEX","139","1","4");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-140","SV04","AltariaEX","140","1","4");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-141","SV04","Tatsugiri","141","1","2");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-142","SV04","Porygon","142","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-143","SV04","Porygon2","143","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-144","SV04","Porygon-Z","144","1","3");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-145","SV04","Aipom","145","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-146","SV04","Ambipom","146","1","2");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-147","SV04","Miltank","147","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-148","SV04","Whismur","148","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-149","SV04","Loudred","149","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-150","SV04","Exploud","150","1","2");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-151","SV04","Spinda","151","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-152","SV04","Swablu","152","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-153","SV04","Tandemaus","153","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-154","SV04","Tandemaus","154","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-155","SV04","MausholdEX","155","1","4");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-156","SV04","BombirdierEX","156","1","4");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-157","SV04","Cyclizar","157","1","2");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-158","SV04","Iron Jugulis","158","1","3");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-159","SV04","Ancient Booster Energy Capsule","159","2","2");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-160","SV04","Counter Catcher","160","2","2");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-161","SV04","Cursed Duster","161","2","2");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-162","SV04","Defiance Vest","162","2","2");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-163","SV04","Earthen Vessel","163","2","2");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-164","SV04","Future Booster Energy Capsule","164","2","2");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-165","SV04","Larry","165","2","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-166","SV04","Luxurious Cape","166","2","2");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-167","SV04","Mela","167","2","2");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-168","SV04","Norman","168","2","2");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-169","SV04","Parasol Lady","169","2","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-170","SV04","Professor Sada's Vitality","170","2","2");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-171","SV04","Professor Turo's Scenario","171","2","2");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-172","SV04","Rika","172","2","2");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-173","SV04","Roark","173","2","2");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-174","SV04","Shauntal","174","2","2");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-175","SV04","Snorlax Doll","175","2","2");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-176","SV04","Technical Machine: Blindside","176","2","2");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-177","SV04","Technical Machine: Devolution","177","2","2");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-178","SV04","Technical Machine: Evolution","178","2","2");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-179","SV04","Technical Machine: Turbo Energize","179","2","2");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-180","SV04","Techno Radar","180","2","2");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-181","SV04","Tulip","181","2","2");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-182","SV04","Medical Energy","182","3","2");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-183","SV04","Crustle","183","1","5");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-184","SV04","Dottler","184","1","5");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-185","SV04","Toedscruel","185","1","5");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-186","SV04","Magby","186","1","5");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-187","SV04","Iron Moth","187","1","5");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-188","SV04","Snorunt","188","1","5");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-189","SV04","Mantyke","189","1","5");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-190","SV04","Vanillish","190","1","5");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-191","SV04","Wimpod","191","1","5");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-192","SV04","Veluza","192","1","5");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-193","SV04","Plusle","193","1","5");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-194","SV04","Minun","194","1","5");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-195","SV04","Blitzle","195","1","5");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-196","SV04","Joltik","196","1","5");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-197","SV04","Espathra","197","1","5");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-198","SV04","Gimmighoul","198","1","5");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-199","SV04","Groudon","199","1","5");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-200","SV04","Mienshao","200","1","5");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-201","SV04","Minior","201","1","5");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-202","SV04","Garganacl","202","1","5");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-203","SV04","Slither Wing","203","1","5");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-204","SV04","Garbodor","204","1","5");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-205","SV04","Yveltal","205","1","5");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-206","SV04","Morpeko","206","1","5");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-207","SV04","Brute Bonnet","207","1","5");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-208","SV04","Steelix","208","1","5");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-209","SV04","Ferrothorn","209","1","5");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-210","SV04","Aegislash","210","1","5");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-211","SV04","Aipom","211","1","5");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-212","SV04","Loudred","212","1","5");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-213","SV04","Swablu","213","1","5");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-214","SV04","Porygon-Z","214","1","5");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-215","SV04","Cyclizar","215","1","5");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-216","SV04","Iron Jugulis","216","1","5");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-217","SV04","FroslassEX","217","1","6");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-218","SV04","ArmarougeEX","218","1","6");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-219","SV04","GarchompEX","219","1","6");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-220","SV04","Tsareena","220","1","6");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-221","SV04","GolisopodEX","221","1","6");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-222","SV04","Tapu KokoEX","222","1","6");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-223","SV04","Iron HandsEX","223","1","6");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-224","SV04","CofagrigusEX","224","1","6");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-225","SV04","Iron ValiantEX","225","1","6");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-226","SV04","HoopaEX","226","1","6");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-227","SV04","ToxtricityEX","227","1","6");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-228","SV04","Sandy ShocksEX","228","1","6");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-229","SV04","Roaring MoonEX","229","1","6");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-230","SV04","AegislashEX","230","1","6");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-231","SV04","GholdengoEX","231","1","6");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-232","SV04","AltariaEX","232","1","6");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-233","SV04","MausholdEX","233","1","6");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-234","SV04","BombirdierEX","234","1","6");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-235","SV04","Larry","235","2","6");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-236","SV04","Mela","236","2","6");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-237","SV04","Norman","237","2","6");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-238","SV04","Parasol Lady","238","2","6");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-239","SV04","Professor Sada's Vitality","239","2","6");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-240","SV04","Professor Turo's Scenario","240","2","6");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-241","SV04","Rika","241","2","6");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-242","SV04","Roark","242","2","6");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-243","SV04","Shauntal","243","2","6");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-244","SV04","Tulip","244","2","6");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-245","SV04","GarchompEX","245","1","7");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-246","SV04","GolisopodEX","246","1","7");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-247","SV04","Tapu KokoEX","247","1","7");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-248","SV04","Iron HandsEX","248","1","7");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-249","SV04","Iron ValiantEX","249","1","7");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-250","SV04","Sandy ShocksEX","250","1","7");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-251","SV04","Roaring MoonEX","251","1","7");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-252","SV04","GholdengoEX","252","1","7");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-253","SV04","AltariaEX","253","1","7");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-254","SV04","Mela","254","2","7");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-255","SV04","Parasol Lady","255","2","7");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-256","SV04","Professor Sada's Vitality","256","2","7");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-257","SV04","Professor Turo's Scenario","257","2","7");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-258","SV04","Rika","258","2","7");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-259","SV04","Tulip","259","2","7");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-260","SV04","GarchompEX","260","1","8");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-261","SV04","Iron ValiantEX","261","1","8");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-262","SV04","Roaring MoonEX","262","1","8");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-263","SV04","Beach Court","263","2","8");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-264","SV04","Counter Catcher","264","2","8");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-265","SV04","Luxurious Cape","265","2","8");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAR-266","SV04","Reversal Energy","266","3","8");