INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("DRI-001","SV10","Ethan's Pinsir","1","1","2");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("DRI-002","SV10","Yanma","2","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("DRI-003","SV10","YanmegaEX","3","1","4");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("DRI-004","SV10","Pineco","4","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("DRI-005","SV10","Shroomish","5","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("DRI-006","SV10","Breloom","6","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("DRI-007","SV10","Cynthia's Roselia","7","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("DRI-008","SV10","Cynthia's Roserade","8","1","3");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("DRI-009","SV10","Mow Rotom","9","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("DRI-010","SV10","Shaymin","10","1","2");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("DRI-011","SV10","Dwebble","11","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("DRI-012","SV10","Crustle","12","1","3");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("DRI-013","SV10","Fomantis","13","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("DRI-014","SV10","Lurantis","14","1","2");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("DRI-015","SV10","Team Rocket's Blipbug","15","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("DRI-016","SV10","Applin","16","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("DRI-017","SV10","Dipplin","17","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("DRI-018","SV10","Hydrapple","18","1","3");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("DRI-019","SV10","Team Rocket's Tarountula","19","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("DRI-020","SV10","Team Rocket's Spidops","20","1","3");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("DRI-021","SV10","Smoliv","21","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("DRI-022","SV10","Dolliv","22","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("DRI-023","SV10","ArbolivaEX","23","1","4");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("DRI-024","SV10","Rellor","24","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("DRI-025","SV10","RabscaEX","25","1","4");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("DRI-026","SV10","Teal Mask Ogerpon","26","1","2");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("DRI-027","SV10","Growlithe","27","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("DRI-028","SV10","Arcanine","28","1","2");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("DRI-029","SV10","Ponyta","29","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("DRI-030","SV10","Rapidash","30","1","2");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("DRI-031","SV10","Team Rocket's MoltresEX","31","1","4");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("DRI-032","SV10","Ethan's Cyndaquil","32","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("DRI-033","SV10","Ethan's Quilava","33","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("DRI-034","SV10","Ethan's Typhlosion","34","1","3");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("DRI-035","SV10","Ethan's Slugma","35","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("DRI-036","SV10","Ethan's Magcargo","36","1","3");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("DRI-037","SV10","Team Rocket's Houndour","37","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("DRI-038","SV10","Team Rocket's Houndoom","38","1","2");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("DRI-039","SV10","Ethan's Ho-OhEX","39","1","4");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("DRI-040","SV10","Torchic","40","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("DRI-041","SV10","Combusken","41","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("DRI-042","SV10","Blaziken","42","1","3");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("DRI-043","SV10","Heat Rotom","43","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("DRI-044","SV10","Hearthflame Mask Ogerpon","44","1","2");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("DRI-045","SV10","Misty's Psyduck","45","1","2");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("DRI-046","SV10","Misty's Staryu","46","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("DRI-047","SV10","Misty's Starmie","47","1","2");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("DRI-048","SV10","Misty's Magikarp","48","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("DRI-049","SV10","Misty's Gyarados","49","1","3");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("DRI-050","SV10","Misty's Lapras","50","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("DRI-051","SV10","Team Rocket's Articuno","51","1","3");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("DRI-052","SV10","Cynthia's Feebas","52","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("DRI-053","SV10","Cynthia's Milotic","53","1","2");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("DRI-054","SV10","Clamperl","54","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("DRI-055","SV10","Huntail","55","1","2");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("DRI-056","SV10","Gorebyss","56","1","3");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("DRI-057","SV10","Buizel","57","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("DRI-058","SV10","Floatzel","58","1","2");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("DRI-059","SV10","Snover","59","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("DRI-060","SV10","Abomasnow","60","1","2");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("DRI-061","SV10","Wash Rotom","61","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("DRI-062","SV10","Arrokuda","62","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("DRI-063","SV10","Barraskewda","63","1","2");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("DRI-064","SV10","Cetoddle","64","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("DRI-065","SV10","CetitanEX","65","1","4");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("DRI-066","SV10","DondozoEX","66","1","4");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("DRI-067","SV10","Wellspring Mask Ogerpon","67","1","2");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("DRI-068","SV10","Electabuzz","68","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("DRI-069","SV10","ElectivireEX","69","1","4");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("DRI-070","SV10","Team Rocket's Zapdos","70","1","3");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("DRI-071","SV10","Ethan's Pichu","71","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("DRI-072","SV10","Team Rocket's Mareep","72","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("DRI-073","SV10","Team Rocket's Flaaffy","73","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("DRI-074","SV10","Team Rocket's Ampharos","74","1","2");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("DRI-075","SV10","Electrike","75","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("DRI-076","SV10","Manectric","76","1","2");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("DRI-077","SV10","Rotom","77","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("DRI-078","SV10","Zeraora","78","1","3");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("DRI-079","SV10","Team Rocket's Drowzee","79","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("DRI-080","SV10","Team Rocket's Hypno","80","1","2");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("DRI-081","SV10","Team Rocket's MewtwoEX","81","1","4");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("DRI-082","SV10","Team Rocket's Wobbuffet","82","1","3");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("DRI-083","SV10","Steven's Baltoy","83","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("DRI-084","SV10","Steven's Claydol","84","1","2");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("DRI-085","SV10","Team Rocket's Chingling","85","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("DRI-086","SV10","Steven's Carbink","86","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("DRI-087","SV10","Team Rocket's Mimikyu","87","1","2");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("DRI-088","SV10","Team Rocket's Dottler","88","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("DRI-089","SV10","Team Rocket's Orbeetle","89","1","2");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("DRI-090","SV10","Mankey","90","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("DRI-091","SV10","Primeape","91","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("DRI-092","SV10","Annihilape","92","1","3");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("DRI-093","SV10","Ethan's Sudowoodo","93","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("DRI-094","SV10","Team Rocket's Larvitar","94","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("DRI-095","SV10","Team Rocket's Pupitar","95","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("DRI-096","SV10","Team Rocket's Tyranitar","96","1","3");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("DRI-097","SV10","Nosepass","97","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("DRI-098","SV10","Probopass","98","1","2");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("DRI-099","SV10","Meditite","99","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("DRI-100","SV10","Medicham","100","1","2");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("DRI-101","SV10","RegirockEX","101","1","4");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("DRI-102","SV10","Cynthia's Gible","102","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("DRI-103","SV10","Cynthia's Gabite","103","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("DRI-104","SV10","Cynthia's GarchompEX","104","1","4");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("DRI-105","SV10","Hippopotas","105","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("DRI-106","SV10","Hippowdon","106","1","2");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("DRI-107","SV10","Mudbray","107","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("DRI-108","SV10","Mudsdale","108","1","2");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("DRI-109","SV10","Arven's Toedscool","109","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("DRI-110","SV10","Arven's Toedscruel","110","1","2");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("DRI-111","SV10","Cornerstone Mask Ogerpon","111","1","2");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("DRI-112","SV10","Team Rocket's Ekans","112","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("DRI-113","SV10","Team Rocket's Arbok","113","1","2");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("DRI-114","SV10","Team Rocket's Nidoran♀","114","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("DRI-115","SV10","Team Rocket's Nidorina","115","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("DRI-116","SV10","Team Rocket's Nidoqueen","116","1","2");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("DRI-117","SV10","Team Rocket's Nidoran♂","117","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("DRI-118","SV10","Team Rocket's Nidorino","118","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("DRI-119","SV10","Team Rocket's NidokingEX","119","1","4");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("DRI-120","SV10","Team Rocket's Zubat","120","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("DRI-121","SV10","Team Rocket's Golbat","121","1","2");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("DRI-122","SV10","Team Rocket's CrobatEX","122","1","4");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("DRI-123","SV10","Team Rocket's Grimer","123","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("DRI-124","SV10","Team Rocket's Muk","124","1","2");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("DRI-125","SV10","Team Rocket's Koffing","125","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("DRI-126","SV10","Team Rocket's Weezing","126","1","2");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("DRI-127","SV10","Team Rocket's Murkrow","127","1","2");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("DRI-128","SV10","Team Rocket's Sneasel","128","1","3");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("DRI-129","SV10","Cynthia's Spiritomb","129","1","2");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("DRI-130","SV10","Marnie's Purrloin","130","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("DRI-131","SV10","Marnie's Liepard","131","1","2");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("DRI-132","SV10","Marnie's Scraggy","132","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("DRI-133","SV10","Marnie's Scrafty","133","1","2");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("DRI-134","SV10","Marnie's Impidimp","134","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("DRI-135","SV10","Marnie's Morgrem","135","1","2");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("DRI-136","SV10","Marnie's GrimmsnarlEX","136","1","4");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("DRI-137","SV10","Marnie's Morpeko","137","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("DRI-138","SV10","Arven's Maschiff","138","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("DRI-139","SV10","Arven's MabosstiffEX","139","1","4");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("DRI-140","SV10","Forretress","140","1","2");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("DRI-141","SV10","Skarmory","141","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("DRI-142","SV10","Steven's Skarmory","142","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("DRI-143","SV10","Steven's Beldum","143","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("DRI-144","SV10","Steven's Metang","144","1","2");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("DRI-145","SV10","Steven's MetagrossEX","145","1","4");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("DRI-146","SV10","Zamazenta","146","1","3");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("DRI-147","SV10","Team Rocket's Rattata","147","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("DRI-148","SV10","Team Rocket's Raticate","148","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("DRI-149","SV10","Team Rocket's Meowth","149","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("DRI-150","SV10","Team Rocket's PersianEX","150","1","4");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("DRI-151","SV10","Kangaskhan","151","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("DRI-152","SV10","Tauros","152","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("DRI-153","SV10","Team Rocket's Porygon","153","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("DRI-154","SV10","Team Rocket's Porygon2","154","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("DRI-155","SV10","Team Rocket's Porygon-Z","155","1","2");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("DRI-156","SV10","Taillow","156","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("DRI-157","SV10","Swellow","157","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("DRI-158","SV10","Arven's Skwovet","158","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("DRI-159","SV10","Arven's Greedent","159","1","3");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("DRI-160","SV10","Squawkabilly","160","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("DRI-161","SV10","Arven's Sandwich","161","2","2");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("DRI-162","SV10","Cynthia's Power Weight","162","2","2");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("DRI-163","SV10","Emcee's Hype","163","2","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("DRI-164","SV10","Energy Recycler","164","2","2");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("DRI-165","SV10","Ethan's Adventure","165","2","2");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("DRI-166","SV10","Granite Cave","166","2","2");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("DRI-167","SV10","Judge","167","2","2");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("DRI-168","SV10","Sacred Ash","168","2","2");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("DRI-169","SV10","Spikemuth Gym","169","2","2");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("DRI-170","SV10","Team Rocket's Archer","170","2","2");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("DRI-171","SV10","Team Rocket's Ariana","171","2","2");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("DRI-172","SV10","Team Rocket's Bother-Bot","172","2","2");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("DRI-173","SV10","Team Rocket's Factory","173","2","2");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("DRI-174","SV10","Team Rocket's Giovanni","174","2","2");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("DRI-175","SV10","Team Rocket's Great Ball","175","2","2");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("DRI-176","SV10","Team Rocket's Petrel","176","2","2");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("DRI-177","SV10","Team Rocket's Proton","177","2","2");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("DRI-178","SV10","Team Rocket's Transceiver","178","2","2");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("DRI-179","SV10","Team Rocket's Venture Bomb","179","2","2");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("DRI-180","SV10","Team Rocket's Watchtower","180","2","2");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("DRI-181","SV10","TM Machine","181","2","2");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("DRI-182","SV10","Team Rocket's Energy","182","3","2");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("DRI-183","SV10","Yanma","183","1","5");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("DRI-184","SV10","Cynthia's Roserade","184","1","5");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("DRI-185","SV10","Shaymin","185","1","5");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("DRI-186","SV10","Crustle","186","1","5");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("DRI-187","SV10","Team Rocket's Spidops","187","1","5");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("DRI-188","SV10","Hydrapple","188","1","5");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("DRI-189","SV10","Rapidash","189","1","5");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("DRI-190","SV10","Ethan's Typhlosion","190","1","5");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("DRI-191","SV10","Team Rocket's Houndoom","191","1","5");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("DRI-192","SV10","Blaziken","192","1","5");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("DRI-193","SV10","Misty's Psyduck","193","1","5");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("DRI-194","SV10","Misty's Lapras","194","1","5");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("DRI-195","SV10","Clamperl","195","1","5");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("DRI-196","SV10","Electrike","196","1","5");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("DRI-197","SV10","Rotom","197","1","5");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("DRI-198","SV10","Team Rocket's Orbeetle","198","1","5");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("DRI-199","SV10","Team Rocket's Weezing","199","1","5");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("DRI-200","SV10","Team Rocket's Murkrow","200","1","5");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("DRI-201","SV10","Zamazenta","201","1","5");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("DRI-202","SV10","Team Rocket's Raticate","202","1","5");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("DRI-203","SV10","Team Rocket's Meowth","203","1","5");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("DRI-204","SV10","Kangaskhan","204","1","5");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("DRI-205","SV10","Arven's Greedent","205","1","5");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("DRI-206","SV10","YanmegaEX","206","1","6");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("DRI-207","SV10","ArbolivaEX","207","1","6");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("DRI-208","SV10","Team Rocket's MoltresEX","208","1","6");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("DRI-209","SV10","Ethan's Ho-OhEX","209","1","6");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("DRI-210","SV10","CetitanEX","210","1","6");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("DRI-211","SV10","DondozoEX","211","1","6");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("DRI-212","SV10","ElectivireEX","212","1","6");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("DRI-213","SV10","Team Rocket's MewtwoEX","213","1","6");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("DRI-214","SV10","RegirockEX","214","1","6");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("DRI-215","SV10","Cynthia's GarchompEX","215","1","6");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("DRI-216","SV10","Team Rocket's NidokingEX","216","1","6");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("DRI-217","SV10","Team Rocket's CrobatEX","217","1","6");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("DRI-218","SV10","Arven's MabosstiffEX","218","1","6");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("DRI-219","SV10","Team Rocket's PersianEX","219","1","6");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("DRI-220","SV10","Emcee's Hype","220","2","6");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("DRI-221","SV10","Ethan's Adventure","221","2","6");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("DRI-222","SV10","Judge","222","2","6");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("DRI-223","SV10","Team Rocket's Archer","223","2","6");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("DRI-224","SV10","Team Rocket's Ariana","224","2","6");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("DRI-225","SV10","Team Rocket's Giovanni","225","2","6");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("DRI-226","SV10","Team Rocket's Petrel","226","2","6");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("DRI-227","SV10","Team Rocket's Proton","227","2","6");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("DRI-228","SV10","YanmegaEX","228","1","7");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("DRI-229","SV10","Team Rocket's MoltresEX","229","1","7");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("DRI-230","SV10","Ethan's Ho-OhEX","230","1","7");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("DRI-231","SV10","Team Rocket's MewtwoEX","231","1","7");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("DRI-232","SV10","Cynthia's GarchompEX","232","1","7");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("DRI-233","SV10","Team Rocket's NidokingEX","233","1","7");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("DRI-234","SV10","Team Rocket's CrobatEX","234","1","7");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("DRI-235","SV10","Arven's MabosstiffEX","235","1","7");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("DRI-236","SV10","Ethan's Adventure","236","2","7");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("DRI-237","SV10","Team Rocket's Ariana","237","2","7");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("DRI-238","SV10","Team Rocket's Giovanni","238","2","7");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("DRI-239","SV10","Ethan's Ho-OhEX","239","1","8");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("DRI-240","SV10","Team Rocket's MewtwoEX","240","1","8");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("DRI-241","SV10","Cynthia's GarchompEX","241","1","8");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("DRI-242","SV10","Team Rocket's CrobatEX","242","1","8");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("DRI-243","SV10","Jamming Tower","243","2","8");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("DRI-244","SV10","Levincia","244","2","8");