INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-001","SV02","Hoppip","1","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-002","SV02","Skiploom","2","1","2");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-003","SV02","Jumpluff","3","1","3");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-004","SV02","Pineco","4","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-005","SV02","ForretressEX","5","1","4");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-006","SV02","Heracross","6","1","2");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-007","SV02","Tropius","7","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-008","SV02","Combee","8","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-009","SV02","Vespiquen","9","1","2");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-010","SV02","Snover","10","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-011","SV02","Abomasnow","11","1","3");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-012","SV02","Sprigatito","12","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-013","SV02","Sprigatito","13","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-014","SV02","Floragato","14","1","2");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-015","SV02","MeowscaradaEX","15","1","4");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-016","SV02","Tarountula","16","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-017","SV02","Tarountula","17","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-018","SV02","Spidops","18","1","2");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-019","SV02","Nymble","19","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-020","SV02","Nymble","20","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-021","SV02","Lokix","21","1","3");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-022","SV02","Bramblin","22","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-023","SV02","Bramblin","23","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-024","SV02","Brambleghast","24","1","2");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-025","SV02","Rellor","25","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-026","SV02","Rellor","26","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-027","SV02","Wo-ChienEX","27","1","4");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-028","SV02","Paldean Tauros","28","1","2");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-029","SV02","Fletchinder","29","1","2");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-030","SV02","Talonflame","30","1","2");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-031","SV02","Litleo","31","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-032","SV02","Pyroar","32","1","2");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-033","SV02","Oricorio","33","1","3");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-034","SV02","Fuecoco","34","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-035","SV02","Fuecoco","35","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-036","SV02","Crocalor","36","1","2");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-037","SV02","SkeledirgeEX","37","1","4");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-038","SV02","Charcadet","38","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-039","SV02","Charcadet","39","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-040","SV02","Chi-YuEX","40","1","4");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-041","SV02","Paldean Tauros","41","1","2");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-042","SV02","Magikarp","42","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-043","SV02","Gyarados","43","1","3");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-044","SV02","Marill","44","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-045","SV02","Azumarill","45","1","2");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-046","SV02","Delibird","46","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-047","SV02","Luvdisc","47","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-048","SV02","Eiscue","48","1","2");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-049","SV02","Quaxly","49","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-050","SV02","Quaxly","50","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-051","SV02","Quaxwell","51","1","2");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-052","SV02","QuaquavalEX","52","1","4");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-053","SV02","Cetoddle","53","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-054","SV02","Cetoddle","54","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-055","SV02","Cetitan","55","1","2");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-056","SV02","Veluza","56","1","3");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-057","SV02","Frigibax","57","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-058","SV02","Frigibax","58","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-059","SV02","Arctibax","59","1","2");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-060","SV02","Baxcalibur","60","1","3");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-061","SV02","Chien-PaoEX","61","1","4");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-062","SV02","Pikachu","62","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-063","SV02","PikachuEX","63","1","4");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-064","SV02","Raichu","64","1","2");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-065","SV02","Magnemite","65","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-066","SV02","Voltorb","66","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-067","SV02","Electrode","67","1","2");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-068","SV02","Shinx","68","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-069","SV02","Shinx","69","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-070","SV02","Luxio","70","1","2");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-071","SV02","Luxray","71","1","3");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-072","SV02","Pincurchin","72","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-073","SV02","Pincurchin","73","1","2");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-074","SV02","Pawmi","74","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-075","SV02","Pawmo","75","1","2");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-076","SV02","Pawmot","76","1","3");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-077","SV02","Tadbulb","77","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-078","SV02","Tadbulb","78","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-079","SV02","BelliboltEX","79","1","4");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-080","SV02","Wattrel","80","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-081","SV02","Wattrel","81","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-082","SV02","Kilowattrel","82","1","2");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-083","SV02","Jigglypuff","83","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-084","SV02","Wigglytuff","84","1","3");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-085","SV02","Slowpoke","85","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-086","SV02","SlowkingEX","86","1","4");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-087","SV02","Misdreavus","87","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-088","SV02","Mismagius","88","1","2");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-089","SV02","Spiritomb","89","1","3");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-090","SV02","Gothita","90","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-091","SV02","Gothorita","91","1","2");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-092","SV02","Gothitelle","92","1","2");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-093","SV02","DedenneEX","93","1","4");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-094","SV02","Oranguru","94","1","2");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-095","SV02","Sandygast","95","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-096","SV02","Palossand","96","1","2");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-097","SV02","Mimikyu","97","1","3");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-098","SV02","Ceruledge","98","1","3");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-099","SV02","Rabsca","99","1","3");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-100","SV02","Tinkatink","100","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-101","SV02","Tinkatink","101","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-102","SV02","Tinkatink","102","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-103","SV02","Tinkatuff","103","1","2");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-104","SV02","Tinkatuff","104","1","2");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-105","SV02","Tinkaton","105","1","3");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-106","SV02","Mankey","106","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-107","SV02","Primeape","107","1","2");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-108","SV02","Paldean Tauros","108","1","2");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-109","SV02","Sudowoodo","109","1","2");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-110","SV02","Larvitar","110","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-111","SV02","Pupitar","111","1","2");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-112","SV02","Makuhita","112","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-113","SV02","Hariyama","113","1","3");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-114","SV02","Croagunk","114","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-115","SV02","Toxicroak","115","1","2");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-116","SV02","Rockruff","116","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-117","SV02","LycanrocEX","117","1","4");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-118","SV02","Passimian","118","1","2");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-119","SV02","Falinks","119","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-120","SV02","Nacli","120","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-121","SV02","Nacli","121","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-122","SV02","Naclstack","122","1","2");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-123","SV02","Garganacl","123","1","3");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-124","SV02","Glimmet","124","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-125","SV02","Glimmet","125","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-126","SV02","Glimmora","126","1","3");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-127","SV02","Ting-LuEX","127","1","4");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-128","SV02","Paldean Wooper","128","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-129","SV02","Paldean Wooper","129","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-130","SV02","Paldean ClodsireEX","130","1","4");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-131","SV02","Murkrow","131","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-132","SV02","Honchkrow","132","1","2");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-133","SV02","Sneasel","133","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-134","SV02","Weavile","134","1","3");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-135","SV02","Tyranitar","135","1","3");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-136","SV02","Sableye","136","1","3");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-137","SV02","Seviper","137","1","2");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-138","SV02","Deino","138","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-139","SV02","Zweilous","139","1","2");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-140","SV02","Hydreigon","140","1","3");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-141","SV02","Maschiff","141","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-142","SV02","Maschiff","142","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-143","SV02","Mabosstiff","143","1","2");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-144","SV02","Shroodle","144","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-145","SV02","Shroodle","145","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-146","SV02","Grafaiai","146","1","2");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-147","SV02","Bombirdier","147","1","2");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-148","SV02","Corviknight","148","1","2");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-149","SV02","Cufant","149","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-150","SV02","CopperajahEX","150","1","4");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-151","SV02","Orthworm","151","1","3");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-152","SV02","Noibat","152","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-153","SV02","NoivernEX","153","1","4");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-154","SV02","Girafarig","154","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-155","SV02","Farigiraf","155","1","2");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-156","SV02","Dunsparce","156","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-157","SV02","Dudunsparce","157","1","2");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-158","SV02","Wingull","158","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-159","SV02","Pelipper","159","1","2");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-160","SV02","Slakoth","160","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-161","SV02","Vigoroth","161","1","2");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-162","SV02","Slaking","162","1","3");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-163","SV02","Fletchling","163","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-164","SV02","Rookidee","164","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-165","SV02","Corvisquire","165","1","2");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-166","SV02","Tandemaus","166","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-167","SV02","Tandemaus","167","1","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-168","SV02","Maushold","168","1","2");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-169","SV02","SquawkabillyEX","169","1","4");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-170","SV02","Flamigo","170","1","2");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-171","SV02","Artazon","171","2","2");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-172","SV02","Boss's Orders [Ghetsis]","172","2","3");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-173","SV02","Bravery Charm","173","2","2");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-174","SV02","Calamitous Snowy Mountain","174","2","2");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-175","SV02","Calamitous Wasteland","175","2","2");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-176","SV02","Choice Belt","176","2","2");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-177","SV02","Clavell","177","2","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-178","SV02","Delivery Drone","178","2","2");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-179","SV02","Dendra","179","2","2");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-180","SV02","Falkner","180","2","2");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-181","SV02","Fighting Au Lait","181","2","2");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-182","SV02","Giacomo","182","2","2");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-183","SV02","Great Ball","183","2","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-184","SV02","Grusha","184","2","2");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-185","SV02","Iono","185","2","2");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-186","SV02","Practice Studio","186","2","2");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-187","SV02","Saguaro","187","2","2");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-188","SV02","Super Rod","188","2","1");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-189","SV02","Superior Energy Retrieval","189","2","2");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-190","SV02","Jet Energy","190","3","2");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-191","SV02","Luminous Energy","191","3","2");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-192","SV02","Reversal Energy","192","3","2");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-193","SV02","Therapeutic Energy","193","3","2");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-194","SV02","Heracross","194","1","5");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-195","SV02","Tropius","195","1","5");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-196","SV02","Sprigatito","196","1","5");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-197","SV02","Floragato","197","1","5");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-198","SV02","Bramblin","198","1","5");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-199","SV02","Fletchinder","199","1","5");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-200","SV02","Pyroar","200","1","5");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-201","SV02","Fuecoco","201","1","5");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-202","SV02","Crocalor","202","1","5");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-203","SV02","Magikarp","203","1","5");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-204","SV02","Marill","204","1","5");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-205","SV02","Eiscue","205","1","5");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-206","SV02","Quaxly","206","1","5");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-207","SV02","Quaxwell","207","1","5");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-208","SV02","Frigibax","208","1","5");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-209","SV02","Arctibax","209","1","5");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-210","SV02","Baxcalibur","210","1","5");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-211","SV02","Raichu","211","1","5");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-212","SV02","Mismagius","212","1","5");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-213","SV02","Gothorita","213","1","5");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-214","SV02","Sandygast","214","1","5");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-215","SV02","Rabsca","215","1","5");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-216","SV02","Tinkatink","216","1","5");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-217","SV02","Tinkatuff","217","1","5");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-218","SV02","Paldean Tauros","218","1","5");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-219","SV02","Sudowoodo","219","1","5");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-220","SV02","Nacli","220","1","5");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-221","SV02","Paldean Wooper","221","1","5");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-222","SV02","Tyranitar","222","1","5");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-223","SV02","Grafaiai","223","1","5");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-224","SV02","Orthworm","224","1","5");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-225","SV02","Rookidee","225","1","5");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-226","SV02","Maushold","226","1","5");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-227","SV02","Flamigo","227","1","5");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-228","SV02","Farigiraf","228","1","5");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-229","SV02","Dudunsparce","229","1","5");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-230","SV02","ForretressEX","230","1","6");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-231","SV02","MeowscaradaEX","231","1","6");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-232","SV02","Wo-ChienEX","232","1","6");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-233","SV02","SkeledirgeEX","233","1","6");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-234","SV02","Chi-YuEX","234","1","6");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-235","SV02","QuaquavalEX","235","1","6");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-236","SV02","Chien-PaoEX","236","1","6");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-237","SV02","BelliboltEX","237","1","6");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-238","SV02","SlowkingEX","238","1","6");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-239","SV02","DedenneEX","239","1","6");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-240","SV02","TinkatonEX","240","1","6");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-241","SV02","LycanrocEX","241","1","6");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-242","SV02","AnnihilapeEX","242","1","6");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-243","SV02","Ting-LuEX","243","1","6");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-244","SV02","Paldean ClodsireEX","244","1","6");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-245","SV02","CopperajahEX","245","1","6");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-246","SV02","NoivernEX","246","1","6");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-247","SV02","SquawkabillyEX","247","1","6");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-248","SV02","Boss's Orders [Ghetsis]","248","2","6");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-249","SV02","Clavell","249","2","6");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-250","SV02","Dendra","250","2","6");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-251","SV02","Falkner","251","2","6");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-252","SV02","Giacomo","252","2","6");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-253","SV02","Grusha","253","2","6");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-254","SV02","Iono","254","2","6");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-255","SV02","Saguaro","255","2","6");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-256","SV02","MeowscaradaEX","256","1","7");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-257","SV02","Wo-ChienEX","257","1","7");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-258","SV02","SkeledirgeEX","258","1","7");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-259","SV02","Chi-YuEX","259","1","7");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-260","SV02","QuaquavalEX","260","1","7");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-261","SV02","Chien-PaoEX","261","1","7");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-262","SV02","TinkatonEX","262","1","7");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-263","SV02","Ting-LuEX","263","1","7");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-264","SV02","SquawkabillyEX","264","1","7");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-265","SV02","Boss's Orders [Ghetsis]","265","2","7");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-266","SV02","Dendra","266","2","7");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-267","SV02","Giacomo","267","2","7");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-268","SV02","Grusha","268","2","7");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-269","SV02","Iono","269","2","7");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-270","SV02","Saguaro","270","2","7");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-271","SV02","MeowscaradaEX","271","1","8");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-272","SV02","SkeledirgeEX","272","1","8");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-273","SV02","QuaquavalEX","273","1","8");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-274","SV02","Chien-PaoEX","274","1","8");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-275","SV02","Ting-LuEX","275","1","8");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-276","SV02","Super Rod","276","2","8");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-277","SV02","Superior Energy Retrieval","277","2","8");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-278","SV02","Basic Grass Energy","278","3","8");
INSERT INTO CARD(Card_ID, Set_Code, Card_Name, Card_Number, Category_ID, Rarity_ID) values("PAL-279","SV02","Basic Water Energy","279","3","8");